In [46]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn import linear_model as lm
%matplotlib inline

In [6]:
dtype_dict = {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float, 'grade':int,
              'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 'long':float, 'sqft_lot15':float,
              'sqft_living':float, 'floors':str, 'condition':int,
              'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int}
data = pd.read_csv('kc_house_data.csv',dtype=dtype_dict)
data_test = pd.read_csv('wk3_kc_house_test_data.csv',dtype=dtype_dict)
data_train = pd.read_csv('wk3_kc_house_train_data.csv',dtype=dtype_dict)
data_validation = pd.read_csv('wk3_kc_house_valid_data.csv',dtype=dtype_dict)
data_subset_1 = pd.read_csv('wk3_kc_house_set_1_data.csv',dtype=dtype_dict)
data_subset_2 = pd.read_csv('wk3_kc_house_set_2_data.csv',dtype=dtype_dict)
data_subset_3 = pd.read_csv('wk3_kc_house_set_3_data.csv',dtype=dtype_dict)
data_subset_4 = pd.read_csv('wk3_kc_house_set_4_data.csv',dtype=dtype_dict)

In [7]:
data.head(10)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3.0,1.00,1180.0,5650,1,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340.0,5650.0
1,6414100192,20141209T000000,538000.0,3.0,2.25,2570.0,7242,2,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690.0,7639.0
2,5631500400,20150225T000000,180000.0,2.0,1.00,770.0,10000,1,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720.0,8062.0
3,2487200875,20141209T000000,604000.0,4.0,3.00,1960.0,5000,1,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360.0,5000.0
4,1954400510,20150218T000000,510000.0,3.0,2.00,1680.0,8080,1,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800.0,7503.0
5,7237550310,20140512T000000,1225000.0,4.0,4.50,5420.0,101930,1,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760.0,101930.0
6,1321400060,20140627T000000,257500.0,3.0,2.25,1715.0,6819,2,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238.0,6819.0
7,2008000270,20150115T000000,291850.0,3.0,1.50,1060.0,9711,1,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650.0,9711.0
8,2414600126,20150415T000000,229500.0,3.0,1.00,1780.0,7470,1,0,0,...,7,1050,730,1960,0,98146,47.5123,-122.337,1780.0,8113.0
9,3793500160,20150312T000000,323000.0,3.0,2.50,1890.0,6560,2,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390.0,7570.0

# A function that returns the column raised to the given power

In [64]:
def power(feature,degree):
    my_data_frame = pd.DataFrame()
    my_data_frame['feature'] = np.power(feature,degree)
    return my_data_frame

# A polynomial data frame that takes feature and degree and returns dataframe with feature polynomial

In [65]:
def polynomial_dataframe(feature,degree):
    my_data_frame = pd.DataFrame()
    for x in range(1,degree + 1):
        my_data_frame['Feature_%s' %x] = np.power(feature,x)
    return my_data_frame

In [62]:
data = data.sort(['sqft_living','price'])

/home/om/gl-env/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

TypeError: 'Series' objects are mutable, thus they cannot be hashed

## poly1_data = polynomial_dataframe(data['sqft_living'],1)
poly1_data['price'] = data['price']
len(data['price'])

In [78]:
model1 = lm.LinearRegression()
model1.fit(np.array(poly1_data['Feature_1'].reshape(21613),poly1_data['price'])

SyntaxError: invalid syntax (<ipython-input-78-bf99c9e42ffd>, line 2)